services:
  redis-server:
    image: redis:7.2.4
    environment: 
      - REDIS_ARGS=--save 30 1
      # snapshot
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    post_start:
      - command: /scripts/load.sh

  webapp:
    build: .
    image: restos
    
    ports:
      - 8080:8080 
    environment:
      - MESSAGE=🎉 Hello from 🐳 Compose 👋
      - TITLE=My favorite restaurants
      - REDIS_URL=redis-server:6379    
    depends_on:
      - redis-server 
    develop:
      watch:
        - action: sync
          path: ./public
          target: /app/public
        # To be uncommented with DD 2.40
        - action: rebuild
          path: .
          include: ["*.go", "Dockerfile"]
        

volumes:
  redis-data:
